application: biddsat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /files
  static_dir: files

- url: /meta
  static_dir: meta

- url: /icons
  static_dir: icons

- url: /.*
  script: biddsat.app
